#155 | The infrastructure for Pagination, Order, and Filter has been created.
gelecekbilimde/backend pull request #158
Opened 2024-10-01 11:24 UTC by MenekseYuncu

2024-10-01 13:12 UTC, MenekseYuncu commented on src/main/java/org/gelecekbilimde/scienceplatform/common/model/BasePageable.java
> +
@coderabbitai import java.util.Collections does not include CollectionUtils

2024-10-01 13:31 UTC, MenekseYuncu commented on src/main/java/org/gelecekbilimde/scienceplatform/ticket/service/impl/TicketMessageServiceImpl.java
> +		final BasePage<TicketMessageResponse> messageResponsesPage = BasePage.of(messagePage, ticketMessageRespons);
@coderabbitai This part will be corrected later.

2024-10-01 13:35 UTC, MenekseYuncu commented on src/main/java/org/gelecekbilimde/scienceplatform/common/model/BasePageable.java
> +	private int pageSize;
@aleyna-yildizli @Ciklamert page ve pageSize max kaç olmalı ? ben max = 99999999 verdim ama ne kadar doğru bilemedim

2024-10-01 19:40 UTC, agitrubard requested changes

2024-10-01 19:40 UTC, agitrubard commented on src/main/java/org/gelecekbilimde/scienceplatform/common/model/BasePageable.java
> +	@Range(min = 1, max = 10)
Şimdilik 10 olarak sabitleyelim diye düşünüyorum. Sonra duruma göre dinamikleştirilirse düzeltelim ✅ 
```suggestion
	@Range(min = 10, max = 10)
```

2024-10-01 19:40 UTC, agitrubard commented on src/main/java/org/gelecekbilimde/scienceplatform/post/model/request/AdminPostListRequest.java
>  	public Boolean isActive;
Bu alanı Filter içerisine kapsülleyebilir miyiz? Bu sayede yapı görünmüş olur ✅

2024-10-01 19:40 UTC, agitrubard commented on src/main/java/org/gelecekbilimde/scienceplatform/ticket/model/request/TicketMessageRequest.java
>  	private Integer id;
Bu alanı Filter içerisine kapsülleyebilir miyiz? Bu sayede yapı görünmüş olur ✅

2024-10-03 08:47 UTC, agitrubard approved these changes

2024-10-03 08:48 UTC, merged